services:
  # Backend (Flask)
  - name: fullstack-backend
    type: web
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    # Ejecuta migraciones y luego arranca Gunicorn
    startCommand: flask --app app:create_app db upgrade && gunicorn -w 2 -b 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: CORS_ORIGINS
        # Actualiza luego con la URL real del frontend
        value: https://<tu-frontend>.onrender.com

  # Frontend (Vite → static)
  - name: fullstack-frontend
    type: web
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        # Actualiza luego con la URL real del backend
        value: https://<tu-backend>.onrender.com
