[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["migrations", ".venv"]

[tool.ruff.lint]
select = ["E", "F", "I"]  # pycodestyle, Pyflakes, isort
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["app"]
